language: java
jdk: oraclejdk8
sudo: false
 
cache:
  directories:
    - ~/.m2
before_cache:
  - rm -rf ~/.m2/repository/org/universAAL

branches: 
 only:
 - master

env:
  global:
    secure: "VHNp7pNsYvtj4dnMAMjNemdiquwaAsq0xRxlZCrFBmsnSap++xITJdym6Kvhy2VB1IfOWYr1j/O32unpeFrrbZMKpZR2c70iXePduPPFJQ+tkDuGNA8XZavumqZ/JASjcx+jb5TgQXTwSQAyh1ctutzfbcGeHb3635VlMNYwXiY="

addons:
  apt:
    packages:
      - graphviz

before_install:
 - cd ri.pom
 - (curl -s https://raw.githubusercontent.com/universAAL/platform/master/uAAL.pom/src/scripts/settings.xml) > settings.xml
 - cp settings.xml $HOME/.m2/settings.xml
 - (curl -s https://raw.githubusercontent.com/universAAL/platform/master/uAAL.pom/src/scripts/ci.sh) > ci.sh
 - chmod +x ci.sh
 - export MY_REPO="remote"

install:
 -

before_script:
 - cat /etc/mavenrc
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

script:
 - ./ci.sh script

after_success:
 - ./ci.sh success

notifications:
  email: false
