
package org.universAAL.commerce.ustore.tools;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2012-12-17T15:40:04.932+02:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "uAALException", targetNamespace = "http://tools.ustore.commerce.universaal.org/")
public class UAALException_Exception extends Exception {
    
    private org.universAAL.commerce.ustore.tools.UAALException uAALException;

    public UAALException_Exception() {
        super();
    }
    
    public UAALException_Exception(String message) {
        super(message);
    }
    
    public UAALException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UAALException_Exception(String message, org.universAAL.commerce.ustore.tools.UAALException uAALException) {
        super(message);
        this.uAALException = uAALException;
    }

    public UAALException_Exception(String message, org.universAAL.commerce.ustore.tools.UAALException uAALException, Throwable cause) {
        super(message, cause);
        this.uAALException = uAALException;
    }

    public org.universAAL.commerce.ustore.tools.UAALException getFaultInfo() {
        return this.uAALException;
    }
}
